 [theme]
 # primary accent color for interactive elements.
 primarycolor = "#d33682"

 # background color for the main content area.
 backgroundColor = "#002b36"

 # Background color used for the sidebar and most inrteractive widgets.
 secondaryBackgroundColor = "#586e75"

 # Color used for almost all text.
 textcolor = '#fff"